# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\menu_u.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(762, 492)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/graduation-cap-free-icon-font.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("border:none;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_superior = QtWidgets.QFrame(self.centralwidget)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_superior.setStyleSheet("\n"
"QFrame{\n"
"background-color: black;\n"
"\n"
"}\n"
"")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_8.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.bt_menu = QtWidgets.QPushButton(self.frame_superior)
        self.bt_menu.setMinimumSize(QtCore.QSize(200, 0))
        self.bt_menu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.bt_menu.setStyleSheet("QPushButton{\n"
"background-color: Black;\n"
"font: 87 12pt \"Arial Black\";\n"
"color: #E6D61B;\n"
"border-radius:0px;\n"
"}\n"
"")
        self.bt_menu.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_menu.setIcon(icon1)
        self.bt_menu.setIconSize(QtCore.QSize(16, 16))
        self.bt_menu.setAutoDefault(False)
        self.bt_menu.setDefault(False)
        self.bt_menu.setFlat(False)
        self.bt_menu.setObjectName("bt_menu")
        self.horizontalLayout_8.addWidget(self.bt_menu, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(265, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.bt_minimizar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_minimizar.setMinimumSize(QtCore.QSize(35, 35))
        self.bt_minimizar.setStyleSheet("border: none;\n"
"")
        self.bt_minimizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/fabajo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_minimizar.setIcon(icon2)
        self.bt_minimizar.setIconSize(QtCore.QSize(16, 16))
        self.bt_minimizar.setFlat(False)
        self.bt_minimizar.setObjectName("bt_minimizar")
        self.horizontalLayout_8.addWidget(self.bt_minimizar, 0, QtCore.Qt.AlignRight)
        self.bt_restaurar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_restaurar.setMaximumSize(QtCore.QSize(35, 35))
        self.bt_restaurar.setStyleSheet("border: none;\n"
"")
        self.bt_restaurar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_restaurar.setIcon(icon3)
        self.bt_restaurar.setIconSize(QtCore.QSize(16, 16))
        self.bt_restaurar.setObjectName("bt_restaurar")
        self.horizontalLayout_8.addWidget(self.bt_restaurar, 0, QtCore.Qt.AlignRight)
        self.bt_maximizar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_maximizar.setMaximumSize(QtCore.QSize(35, 35))
        self.bt_maximizar.setStyleSheet("border: none;\n"
"")
        self.bt_maximizar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/max.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_maximizar.setIcon(icon4)
        self.bt_maximizar.setIconSize(QtCore.QSize(16, 16))
        self.bt_maximizar.setObjectName("bt_maximizar")
        self.horizontalLayout_8.addWidget(self.bt_maximizar, 0, QtCore.Qt.AlignRight)
        self.bt_cerrar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_cerrar.setMaximumSize(QtCore.QSize(35, 16777215))
        self.bt_cerrar.setStyleSheet("border: none;\n"
"")
        self.bt_cerrar.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/cerrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_cerrar.setIcon(icon5)
        self.bt_cerrar.setIconSize(QtCore.QSize(16, 16))
        self.bt_cerrar.setObjectName("bt_cerrar")
        self.horizontalLayout_8.addWidget(self.bt_cerrar, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_superior)
        self.frame_inferior = QtWidgets.QFrame(self.centralwidget)
        self.frame_inferior.setStyleSheet("")
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_inferior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_lateral = QtWidgets.QFrame(self.frame_inferior)
        self.frame_lateral.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_lateral.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_lateral.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_lateral.setAutoFillBackground(False)
        self.frame_lateral.setStyleSheet("\n"
"QFrame{\n"
"background-color: yellow;\n"
"color: black;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton{\n"
"background-color: yellow;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: black;\n"
"font: 75 12pt \"Arial Narrow\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: black;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color:yellow;\n"
"\n"
"font: 75 12pt \"Arial Narrow\";\n"
"}")
        self.frame_lateral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lateral.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_lateral.setObjectName("frame_lateral")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_lateral)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, 9)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bt_inicio = QtWidgets.QPushButton(self.frame_lateral)
        self.bt_inicio.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_inicio.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.bt_inicio.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_inicio.setIconSize(QtCore.QSize(32, 32))
        self.bt_inicio.setObjectName("bt_inicio")
        self.verticalLayout_2.addWidget(self.bt_inicio)
        self.bt_uno = QtWidgets.QPushButton(self.frame_lateral)
        self.bt_uno.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_uno.setToolTipDuration(0)
        self.bt_uno.setStyleSheet("")
        self.bt_uno.setIconSize(QtCore.QSize(32, 32))
        self.bt_uno.setObjectName("bt_uno")
        self.verticalLayout_2.addWidget(self.bt_uno)
        self.bt_dos = QtWidgets.QPushButton(self.frame_lateral)
        self.bt_dos.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_dos.setStyleSheet("")
        self.bt_dos.setIconSize(QtCore.QSize(32, 32))
        self.bt_dos.setObjectName("bt_dos")
        self.verticalLayout_2.addWidget(self.bt_dos)
        self.bt_tres = QtWidgets.QPushButton(self.frame_lateral)
        self.bt_tres.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_tres.setStyleSheet("")
        self.bt_tres.setIconSize(QtCore.QSize(32, 32))
        self.bt_tres.setObjectName("bt_tres")
        self.verticalLayout_2.addWidget(self.bt_tres)
        self.bt_cinco = QtWidgets.QPushButton(self.frame_lateral)
        self.bt_cinco.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_cinco.setStyleSheet("")
        self.bt_cinco.setIconSize(QtCore.QSize(32, 32))
        self.bt_cinco.setObjectName("bt_cinco")
        self.verticalLayout_2.addWidget(self.bt_cinco)
        self.label_2 = QtWidgets.QLabel(self.frame_lateral)
        self.label_2.setStyleSheet("font:15px \"Arial black\";")
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout.addWidget(self.frame_lateral, 0, QtCore.Qt.AlignLeft)
        self.frame_contenedor = QtWidgets.QFrame(self.frame_inferior)
        self.frame_contenedor.setStyleSheet("")
        self.frame_contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contenedor.setLineWidth(1)
        self.frame_contenedor.setObjectName("frame_contenedor")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_contenedor)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_contenedor)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setStyleSheet("background-color:black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.textBrowser = QtWidgets.QTextBrowser(self.page)
        self.textBrowser.setStyleSheet("color: yellow;")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_9.addWidget(self.textBrowser)
        self.stackedWidget.addWidget(self.page)
        self.page_uno = QtWidgets.QWidget()
        self.page_uno.setStyleSheet("")
        self.page_uno.setObjectName("page_uno")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_uno)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.page_uno)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(100, 50))
        self.label_3.setStyleSheet("background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 16pt \"Arial\";\n"
"color: white;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.widget_2 = QtWidgets.QWidget(self.page_uno)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ELK = QtWidgets.QPushButton(self.widget_2)
        self.ELK.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 8pt \"Arial\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: yellow;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color:black;\n"
"font: 87 8pt \"Arial\";\n"
"border: 3px solid;\n"
"border-color: black;\n"
"}")
        self.ELK.setObjectName("ELK")
        self.horizontalLayout_3.addWidget(self.ELK)
        self.vd1 = QtWidgets.QPushButton(self.widget_2)
        self.vd1.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 8pt \"Arial\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: yellow;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color:black;\n"
"font: 87 8pt \"Arial\";\n"
"border: 3px solid;\n"
"border-color: black;\n"
"}")
        self.vd1.setObjectName("vd1")
        self.horizontalLayout_3.addWidget(self.vd1)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.page_uno)
        self.textBrowser_2.setStyleSheet("color:yellow;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_4.addWidget(self.textBrowser_2)
        self.bt_ter1 = QtWidgets.QPushButton(self.page_uno)
        self.bt_ter1.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 16pt \"Arial\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: yellow;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color:black;\n"
"font: 87 16pt \"Arial\";\n"
"border: 3px solid;\n"
"border-color: black;\n"
"}")
        self.bt_ter1.setObjectName("bt_ter1")
        self.verticalLayout_4.addWidget(self.bt_ter1)
        self.bt_prac1 = QtWidgets.QPushButton(self.page_uno)
        self.bt_prac1.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 16pt \"Arial\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: yellow;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color:black;\n"
"font: 87 16pt \"Arial\";\n"
"border: 3px solid;\n"
"border-color: black;\n"
"}")
        self.bt_prac1.setObjectName("bt_prac1")
        self.verticalLayout_4.addWidget(self.bt_prac1)
        self.stackedWidget.addWidget(self.page_uno)
        self.page_dos = QtWidgets.QWidget()
        self.page_dos.setStyleSheet("")
        self.page_dos.setObjectName("page_dos")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_dos)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.page_dos)
        self.label_4.setMaximumSize(QtCore.QSize(100, 50))
        self.label_4.setStyleSheet("background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 16pt \"Arial\";\n"
"color: white;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.widget_3 = QtWidgets.QWidget(self.page_dos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.MISP = QtWidgets.QPushButton(self.widget_3)
        self.MISP.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 8pt \"Arial\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: yellow;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color:black;\n"
"font: 87 8pt \"Arial\";\n"
"border: 3px solid;\n"
"border-color: black;\n"
"}")
        self.MISP.setObjectName("MISP")
        self.horizontalLayout_4.addWidget(self.MISP)
        self.vd2 = QtWidgets.QPushButton(self.widget_3)
        self.vd2.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 8pt \"Arial\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: yellow;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color:black;\n"
"font: 87 8pt \"Arial\";\n"
"border: 3px solid;\n"
"border-color: black;\n"
"}")
        self.vd2.setObjectName("vd2")
        self.horizontalLayout_4.addWidget(self.vd2)
        self.verticalLayout_5.addWidget(self.widget_3)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.page_dos)
        self.textBrowser_3.setStyleSheet("color: yellow;")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout_5.addWidget(self.textBrowser_3)
        self.bt_ter2 = QtWidgets.QPushButton(self.page_dos)
        self.bt_ter2.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 16pt \"Arial\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: yellow;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color:black;\n"
"font: 87 16pt \"Arial\";\n"
"border: 3px solid;\n"
"border-color: black;\n"
"}")
        self.bt_ter2.setObjectName("bt_ter2")
        self.verticalLayout_5.addWidget(self.bt_ter2)
        self.bt_prac2 = QtWidgets.QPushButton(self.page_dos)
        self.bt_prac2.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 16pt \"Arial\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: yellow;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color:black;\n"
"font: 87 16pt \"Arial\";\n"
"border: 3px solid;\n"
"border-color: black;\n"
"}")
        self.bt_prac2.setObjectName("bt_prac2")
        self.verticalLayout_5.addWidget(self.bt_prac2)
        self.stackedWidget.addWidget(self.page_dos)
        self.page_tres = QtWidgets.QWidget()
        self.page_tres.setObjectName("page_tres")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_tres)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.page_tres)
        self.label_5.setMaximumSize(QtCore.QSize(150, 50))
        self.label_5.setStyleSheet("background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 16pt \"Arial\";\n"
"color: white;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.widget_4 = QtWidgets.QWidget(self.page_tres)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.CTZ = QtWidgets.QPushButton(self.widget_4)
        self.CTZ.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 8pt \"Arial\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: yellow;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color:black;\n"
"font: 87 8pt \"Arial\";\n"
"border: 3px solid;\n"
"border-color: black;\n"
"}")
        self.CTZ.setObjectName("CTZ")
        self.horizontalLayout_5.addWidget(self.CTZ)
        self.vd3 = QtWidgets.QPushButton(self.widget_4)
        self.vd3.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 8pt \"Arial\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: yellow;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color:black;\n"
"font: 87 8pt \"Arial\";\n"
"border: 3px solid;\n"
"border-color: black;\n"
"}")
        self.vd3.setObjectName("vd3")
        self.horizontalLayout_5.addWidget(self.vd3)
        self.verticalLayout_6.addWidget(self.widget_4)
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.page_tres)
        self.textBrowser_6.setStyleSheet("color: yellow;")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.verticalLayout_6.addWidget(self.textBrowser_6)
        self.bt_ter3 = QtWidgets.QPushButton(self.page_tres)
        self.bt_ter3.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 16pt \"Arial\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: yellow;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color:black;\n"
"font: 87 16pt \"Arial\";\n"
"border: 3px solid;\n"
"border-color: black;\n"
"}")
        self.bt_ter3.setObjectName("bt_ter3")
        self.verticalLayout_6.addWidget(self.bt_ter3)
        self.bt_prac3 = QtWidgets.QPushButton(self.page_tres)
        self.bt_prac3.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 16pt \"Arial\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: yellow;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color:black;\n"
"font: 87 16pt \"Arial\";\n"
"border: 3px solid;\n"
"border-color: black;\n"
"}")
        self.bt_prac3.setObjectName("bt_prac3")
        self.verticalLayout_6.addWidget(self.bt_prac3)
        self.stackedWidget.addWidget(self.page_tres)
        self.page_cinco = QtWidgets.QWidget()
        self.page_cinco.setStyleSheet("")
        self.page_cinco.setObjectName("page_cinco")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_cinco)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.page_cinco)
        self.label_7.setMaximumSize(QtCore.QSize(175, 50))
        self.label_7.setStyleSheet("background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 16pt \"Arial\";\n"
"color: white;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.PHP = QtWidgets.QPushButton(self.page_cinco)
        self.PHP.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 8pt \"Arial\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: yellow;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color:black;\n"
"font: 87 8pt \"Arial\";\n"
"border: 3px solid;\n"
"border-color: black;\n"
"}")
        self.PHP.setObjectName("PHP")
        self.verticalLayout_8.addWidget(self.PHP)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.page_cinco)
        self.textBrowser_4.setStyleSheet("color: yellow;")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.verticalLayout_8.addWidget(self.textBrowser_4)
        self.bt_ter5 = QtWidgets.QPushButton(self.page_cinco)
        self.bt_ter5.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 16pt \"Arial\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: yellow;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color:black;\n"
"font: 87 16pt \"Arial\";\n"
"border: 3px solid;\n"
"border-color: black;\n"
"}")
        self.bt_ter5.setObjectName("bt_ter5")
        self.verticalLayout_8.addWidget(self.bt_ter5)
        self.bt_prac5 = QtWidgets.QPushButton(self.page_cinco)
        self.bt_prac5.setStyleSheet("QPushButton{\n"
"background-color: black;\n"
"border: 3px solid;\n"
"border-color: yellow;\n"
"font: 87 16pt \"Arial\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: yellow;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color:black;\n"
"font: 87 16pt \"Arial\";\n"
"border: 3px solid;\n"
"border-color: black;\n"
"}")
        self.bt_prac5.setObjectName("bt_prac5")
        self.verticalLayout_8.addWidget(self.bt_prac5)
        self.stackedWidget.addWidget(self.page_cinco)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame_contenedor)
        self.verticalLayout.addWidget(self.frame_inferior)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_inicio.setText(_translate("MainWindow", "              INICIO             "))
        self.bt_uno.setText(_translate("MainWindow", "ELK"))
        self.bt_dos.setText(_translate("MainWindow", "MISP"))
        self.bt_tres.setText(_translate("MainWindow", "CORTEZA"))
        self.bt_cinco.setText(_translate("MainWindow", "PÁGINA CRUD"))
        self.label_2.setText(_translate("MainWindow", "Ahmed - Eduardo"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; text-decoration: underline;\">C.M</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/icons/icons/Portada.png\" /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:26pt; font-weight:600;\">Continens Melius.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:26pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Os presentamos nuestra aplicación elaborada con código Python en la que se incluyen 3 herramientas muy útiles y que seguro que os parecen muy enteresantes y terminando, un juego php que os pondrá a prueba con el objetivo de obtener el control total de la página.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Las herramientas son ELK, MISP y Corteza, todas ellas herramientas orientadas al ámbito empresarial de código abierto. Siempre os podéis informar más a fondo de estas herramientas en las páginas oficiales que os dejaremos en los apartados de la aplicación de la herramienta correspondiente.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Cada apartado continene un pdf explicativo de la instalación de la herramienta y de sus posibles usos, como también una parte de práctica en la que podrás acceder a un docker, con el objetivo de probar brevemente la herramienta y veas la interfaz de cada una y lo que puedes realizar en cada una.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Os agradecemos de antemano utilizar nuestra aplicación.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "ELK"))
        self.ELK.setText(_translate("MainWindow", "Página oficial"))
        self.vd1.setText(_translate("MainWindow", "Vídeo corto explicativo"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">EXPLICACIÓN:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">ELK es una fusión de tres proyectos llamados Elasticsearch, Logstash y Kibana. Elasticsearch está basado en JSON y consiste en ser un motor de búsqueda. Logtash consiste en un programa que recibe la información introducida de múltiples fuentes y la transforma. Kibana sirve como una herramienta para visualizar contenido.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" font-size:9pt;\">Al ver esto el fusionar estos tres proyectos fue una gran idea y que con Elasticsearch se conseguía la búsqueda de los datos, con Logstash que esos datos se reciban y se envíen de forma que con Kibana se puedan visualizar de diversas maneras.</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/icons/icons/ELK.jpg\" /></p></body></html>"))
        self.bt_ter1.setText(_translate("MainWindow", "TEORÍA"))
        self.bt_prac1.setText(_translate("MainWindow", "PRÁCTICA"))
        self.label_4.setText(_translate("MainWindow", "MISP"))
        self.MISP.setText(_translate("MainWindow", "Página oficial"))
        self.vd2.setText(_translate("MainWindow", "Vídeo corto explicativo"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">EXPLICACIÓN:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">MISP (Malware Information Sharing Platform) se basa en el intercambio de infromación sobre amenazas, como malware, ataques dirigidos y más. Dentro de esta plataforma de inteligencia, originalmente desarrollada por las fuerzas belgas, hay comunidades cerradas, semiprivadas y abiertas, donde hay diferentes tipos de informaciones, dependiendo de la que se haya transmitido en cada comunidad.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">A partir de esta información transmitida, MISP, trata de mejorar las contramedidas y acciones contra los ataques o malware que se comparten para ayudar a combatirles. MISP, también va almacenando información sobre cada ataque, y la utiliza para generar reglas NIDS (Network Intrusion Detection System) para que posteriormente se importe al IDS.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">El punto positivo de MISP es que ha conseguido una comunidad con numerosas empresas y organismos, lo que hace que cad vez haya más y más información, lo que la hace mejorar.</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/icons/icons/MISP.jpg\" /></p></body></html>"))
        self.bt_ter2.setText(_translate("MainWindow", "TEORÍA"))
        self.bt_prac2.setText(_translate("MainWindow", "PRÁCTICA"))
        self.label_5.setText(_translate("MainWindow", "CORTEZA"))
        self.CTZ.setText(_translate("MainWindow", "Página oficial"))
        self.vd3.setText(_translate("MainWindow", "Vídeo corto explicativo"))
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">EXPLICACIÓN:</span><br /><span style=\" font-size:9pt;\">Corteza es una plataforma basada en el desarrollo con low code, que cuenta con tecnologías modernas. Es una plataforma confiable y segura, que tiene muy en cuenta el mantenimiento de la misma, y su desarrollo, con el objetivo de que las organizaciones que cuenten con Corteza, sepan que esta va a estar siempre controlada, segura, y con un desarrollo de mejoras contínuo.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Además está bien explicada y tiene una extensa documentación, con el objetivo que el usuario pueda utilizar la herramienta, y sea posible crear y desarrollar en esta.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; color:#0000ff;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/icons/icons/corteza.jpg\" /></p></body></html>"))
        self.bt_ter3.setText(_translate("MainWindow", "TEORÍA"))
        self.bt_prac3.setText(_translate("MainWindow", "PRÁCTICA"))
        self.label_7.setText(_translate("MainWindow", "PÁGINA CRUD"))
        self.PHP.setText(_translate("MainWindow", "Página oficial de PHP"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">EXPLICACIÓN:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PHP es uno de los lenguajes de programación más conocidos actualmente, debido a por su utilidad en la realización de páginas y desarrollo web y se puede implementar en HTML.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lo que que queremos ofrecer en este apartado es un poco diferente a los demás. Siguiendo la teoría y las imágenes, teneís que conseguir realizar, siguiendo el orden de la teoría, diferentes páginas .php, como si fueran niveles, Una vez completadas todas las páginas, ya habriaís acabado este tipo de &quot;juego&quot;.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; color:#0000ff;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/icons/icons/php.png\" /></p></body></html>"))
        self.bt_ter5.setText(_translate("MainWindow", "TEORÍA"))
        self.bt_prac5.setText(_translate("MainWindow", "PRÁCTICA"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
